FROM php:8.3-apache

# Copy source code
COPY ./api/ /srv/app
COPY ./docker/php/ /srv/docker/php
RUN chown -Rf www-data:www-data /srv/app

# Default packages
RUN apt-get update && \
    apt-get install -y curl git wget zip

# MySql
RUN docker-php-ext-install pdo_mysql

# Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Apache
RUN cp /srv/docker/php/conf/001-main.conf /etc/apache2/sites-available/001-main.conf
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf &&\
    a2enmod rewrite &&\
    a2dissite 000-default &&\
    a2ensite 001-main
RUN apache2ctl start

# Set USER
USER www-data
WORKDIR /srv/app
